version: "3"

services:
  web:
    build: .
    command: > 
      sh -c "sleep 20 && python manage.py makemigrations &&                            
      python manage.py migrate && 
      python manage.py runserver 0.0.0.0:8081"
    volumes:
      - .:/voldatabase
    ports:
      - "8001:8000"
    depends_on:
      - db

  db:
    image: mysql:latest
    env_file:
      - .env 
    ports:
      - "3306:3306"  
    volumes:
      - ./mysql-data:/var/lib/mysql
